-- phpMyAdmin SQL Dump
-- version 4.8.3
-- https://www.phpmyadmin.net/
--
-- Máy chủ: 127.0.0.1
-- Thời gian đã tạo: Th1 03, 2019 lúc 05:16 PM
-- Phiên bản máy phục vụ: 10.1.36-MariaDB
-- Phiên bản PHP: 7.2.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Cơ sở dữ liệu: `hopambh`
--

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `baihat`
--

CREATE TABLE `baihat` (
  `Mabh` int(11) NOT NULL,
  `Tenbh` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `Loibh` text COLLATE utf8_unicode_ci NOT NULL,
  `CaSi` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `TacGia` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `TheLoai` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `Dieubh` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `Tone` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `Capo` int(11) NOT NULL,
  `Link` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `CapNhat` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `NguoiDang` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `LuotXem` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `baihat`
--

INSERT INTO `baihat` (`Mabh`, `Tenbh`, `Loibh`, `CaSi`, `TacGia`, `TheLoai`, `Dieubh`, `Tone`, `Capo`, `Link`, `CapNhat`, `NguoiDang`, `LuotXem`) VALUES
(1, 'Thằng Điên', 'Giờ tôi lại [Cmaj7]lang thang tình yêu thì miên man\r\nNgày xanh cùng [Am7]mây tung tăng tựa mình [A7]bên phím đàn\r\n Nhìn em mình [Dm7]ngơ ngác lòng anh chợt hơi khác\r\nTình yêu này <span [F]đến đúng lúc thấy ánh sáng vụt qua [Fm ] \r\n                                        Nụ cười tỏa [Cmaj7]hương nắng bình minh và mây trắng  \r\n Hình như đều [Am7]kêu tôi \"ôi thôi tình yêu đến [A7]rồi!\"                     \r\n Chẳng ai phải [Dm7]thắc mắc còn tôi thì đã chắc           \r\n Nàng ơi nàng [F]hãy đến chiếm lấy tâm hồn [Fm]tôi \r\n\r\n                                     T-ĐK:            \r\n[Em]Mỉm cười lòng chợt bâng khuâng \r\n[Am7]tôi chẳng biết mơ hay thật\r\n  [Dm7]Đợi chờ dù ngày hay đêm [F]anh chỉ cần nghĩ cũng thấy[Fm]vui..\r\n                                          ĐK:    \r\n                  \r\nI\'m in [Cmaj7]love... màu nắng cuốn lấp chân mây mờ xa \r\n                    I\'m in [Am7]love... thành phố chỉ thấy mỗi [A7]riêng mình ta\r\n                      I\'m in [Dm7]love... tựa đầu bên tình yêu mới thiết tha \r\n   Chỉ [F]Crazy man fall in [Fm]love \r\n                                          I\'m in [Cmaj7]love...hạnh phúc chỉ hết khi anh ngừng mơ\r\n       I\'m in [Am7]love... cuộc sống vốn dĩ trôi [A7]như vần thơ \r\n                    I\'m in[Dm7]love... ngả lưng bên cành cây lá xác xơ \r\n  Mờ [F]sương đưa tay anh ôm lấy [Fm]em..\r\n                                         Dẫu biết chỉ là [Cmaj7]mơ.. \r\n Dẫu biết chỉ là [Am7] mơ [A7 ]   \r\n Dẫu biết chỉ là [Dm7]mơ \r\n [F]</span>\"Crazy man fall in [Fm]love..\"', 'Phương Ly, Justa Tee', 'Justa Tee, ViruSs', 'Pop Ballad', 'Ballad', 'C', 5, 'https://mp3.zing.vn/bai-hat/Thang-Dien-JustaTee-Phuong-Ly/ZW9DFW9A.html', '2019-01-03 16:09:04', 'Hải', 14),
(2, 'Càng Níu Giữ Càng Dễ Mất', 'Intro: \r\nNếu [Em]có nơi tôn thờ Tình Yêu Là [Bm]Tất Cả \r\nSẽ có Chốn Vô Vọng để ta buông [Am]mình\r\nsau những tổn thương mãi không [Em]thể hàn gắn... \r\n[Em]Lời chia tay nào chẳng ưu sầu \r\nDồn lại bao nhiêu tổn [Bm]thương, tình yêu gục ngã \r\n[Em]Đừng nhìn tôi và hỏi quá nhiều \r\nVì chuyện tình nào cũng [Bm]tan vậy thôi... \r\nVer 2: \r\nNhiều lần tôi ngỡ mình [G]đã tìm \r\nđược một người say đắm yêu[D/F# ]mình \r\nNgờ đâu quên mất điều [Am]trớ trêu: \r\n\"Càng níu giữ, ta càng dễ[Em ]mất\"\" \r\nCó khi cả cuộc đời[C], chẳng thể nào may mắn[D ] \r\nmãi bên cạnh một [Em]người... \r\nChorus: \r\nTình yêu đâu ai [Em]biết trước \r\nsẽ bao lần lạc Giữa [D]Hồ Nước Mắt? \r\n[C]Nhớ đến nỗi hao gầy, người vẫn [Bm]nỡ buông tay!\r\nTình yêu mong manh [Em]nhất là khi dâng trào! \r\nXoá đi một ký [Bm]ức tàn nhẫn thế nào.. \r\nTừng hơi [C]ấm lỡ trao... [D]giờ vô nghĩa sao? \r\n\r\n\r\n', 'Mr.Siro', 'Mr.Siro', 'Nhạc Trẻ', 'Ballad', 'Em', 0, 'https://beta.mp3.zing.vn/bai-hat/Cang-Niu-Giu-Cang-De-Mat-Mr-Siro/ZW9DCEE6.html', '2019-01-03 16:14:39', 'Hải', 5),
(3, 'Hong Kong 1', 'Và giờ em [C]khóc thì cũng chẳng để làm gì \r\nĐâu phải do anh [Bm]chuyện tình mình mà là vì Em đã trao [Am]ai dòng lệ tràn đầy cầu kì [D ] \r\nNhững năm tháng phai [G]nhòa 1. [C]Nếu... trái tim mình nói [Bm]không nên lời \r\nĐắng cay từng tiếng [Am]yêu xa vời Thế [G]là....... \r\nVà hôm nay em [C]đến Nhưng nắng đâu còn thiết [Bm]tha gọi mời \r\nGió âm thầm lướt [Am ]qua muôn đời [D ] \r\nVì ai vì [G]ai \r\n\r\nĐK: \r\n\r\nVì giờ anh [C ]biết chuyện tình mình chẳng còn gì \r\nKhi nắng xuân [Bm ]sang lời mật ngọt còn thầm thì \r\nEm bước sang [Am ]ngang đợi chờ một điều diệu kì [D ] \r\nNhư lúc ban [G ]đầu \r\nVà giờ em [C ]khóc thì cũng chẳng để làm gì \r\nĐâu phải cho [Bm ]ai chuyện tình mình mà là vì \r\nEm đã trao [Am ]ai dòng lệ tràn đầy cầu kì [D ]\r\n Những năm tháng phai [G ]nhòa 2. [C]Nếu... đóa hoa trồng trước [Bm]kia chưa về \r\nNhánh hương tình thoảng [Am]trên câu thề [D ] \r\nAnh ước [G]rằng Rằng một mai anh [C]đến Anh đón em vào sớm [Bm]mai trong lành \r\nNhưng đó mãi là giấc [Am]mơ không thành [D ] \r\nVì ai vì [G]ai \r\n\r\nĐK: \r\n\r\nVì giờ anh [C ]biết chuyện tình mình chẳng còn gì \r\nKhi nắng xuân [Bm ]sang lời mật ngọt còn thầm thì \r\nEm bước sang [Am ]ngang đợi chờ một điều diệu kì [D ] \r\nNhư lúc ban [G ]đầu Và giờ em [C ]khóc thì cũng chẳng để làm gì \r\nĐâu phải cho [Bm ]ai chuyện tình mình mà là vì \r\nEm đã trao [Am ]ai dòng lệ tràn đầy cầu kì [D ] \r\nNhững năm tháng phai [G ]nhòa', 'Nguyễn Trọng Tài', 'Nguyễn Trọng Tài', 'Nhạc Trẻ', 'Ballad', 'G', 3, 'https://www.youtube.com/watch?v=t7tZFq29lis', '2019-01-03 16:08:56', 'Dương', 25),
(4, 'Chấp Nhận (Rời Bỏ 2)', '  1. Vì sao [Am ]anh chẳng hiểu được rằng em đã [Em ]hy sinh những gì  \r\n\r\nĐể bên [Dm ]anh và thương [G7 ]anh như bây [C ]giờ [E7 ]  \r\nVì sao [Am ]anh chẳng biết được rằng em đã [Em ]yêu anh bằng những gì  \r\n\r\nLà những giấc [Dm ]mơ và thanh [E7 ]xuân của [Am ]em    \r\n\r\n2. Vì có [Am ]lúc em đã tin rằng dù cho tất [Em ]cả có quay lưng lại  \r\n\r\nThì em [Dm ]vẫn [G7 ]có anh kề [C ]bên [E7 ]  \r\n\r\nĐể rồi [Am ]khi nhìn anh chợt buồn và quay bước [Em ]đi chẳng nói điều gì  \r\n\r\nĐể em [Dm ]lại bơ vơ trong [E7 ]chính tình yêu của [Am ]mình    \r\n\r\nĐK:  \r\n\r\nĐâu phải [F ]vì em luôn mỉm [G ]cười mà [Em ]em chẳng biết buồn [Am ]đau  \r\n\r\nĐâu phải [Dm ]vì em luôn mạnh [G7 ]mẽ mà [C ]không có phút yếu mềm  \r\nCũng chỉ [F ]vì em quá yêu [G ]anh cũng chỉ [Em ]vì em quá thương [Am ]anh  \r\nNên em [Dm ]để cho tim tổn [E7 ]thương trong lặng [Am ]im.    \r\n* Nên em [Dm ]nhìn anh quay bước [E7 ]đi trong lặng [Am ]im. ', 'Hòa Minzy', 'An Trịnh', 'Nhạc Trẻ', 'Ballad', 'Bm', 2, 'https://beta.mp3.zing.vn/bai-hat/Chap-Nhan-Hoa-Minzy/ZW9EAI76.html', '2019-01-03 08:56:41', '', 15),
(5, 'Suýt Nữa Thì', 'Suýt [C]nữa thì...anh có thể nói muôn [G/B]vàn lời muốn nói \r\nSuýt [Am]nữa thì...có thể đèo em qua [Em/G]từng hàng phố quen \r\nDòng lưu [Fmaj7]bút năm xưa viết vội \r\n\"Hãy còn [Em7]nhớ nhau đến những ngày [Am7]sau\" \r\nTình [Dm7]yêu đầu tiên anh giữ \r\nVẫn vẹn [G]nguyên nơi con tim này! \r\n\r\n[C]Anh còn nhớ \r\nMỗi lúc tan [G/B]trường ngại ngùng theo em \r\n[Am]Là con phố, có hoa [Em/G]bay \r\nAnh mãi theo sau \r\nKhoảng cách [Fmaj7 ]ấy mà sao xa[G ]quá \r\nChẳng thể [Em7]nào để tới [Am7]bên em \r\nThời thanh [Dm7]xuân anh có \r\nLà những nỗi niềm [G]nuối tiếc \r\n\r\nĐK: \r\nLời chưa [C]nói \r\nAnh thả vào trong cơn [G/B]gió nhắn với mây trời \r\nTình yêu [Am]đó \r\nChỉ riền anh biết anh [Em/G]cũng chẳng mong hơn nhiều! \r\nLiệu rằng [Fmaj7]em còn ai đưa [G]đón \r\nAnh ơ [Em]thờ dõi theo [Am]em \r\nNếu có [Dm7]thể trở về hôm ấy \r\nAnh sẽ chẳng [G6]để phí cơ [G]hội \r\nTừng vòng [C]quay \r\nTrên chiếc xe đạp anh [G/B]đón đưa em ngang qua\r\nThời thanh [Am]xuân \r\nLà ta cùng nhau viết [Em/G]lên những giấc mơ đẹp \r\nMột buổi [Fmaj7]chiều ngập tràn mảnh [G]vỡ \r\nRơi ra [Em]từ hạnh phúc riêng [Am]em \r\nSuýt [Dm7]nữa thì người đã biết \r\nYêu [Fm6]thương một thời anh [G]đã tương [Cmaj7]tư \r\n\r\n', 'Andiez', 'Andiez', 'Nhạc Trẻ', 'Ballad', 'C', 1, 'https://www.youtube.com/watch?v=cUmpJ2zwfVU', '2019-01-03 16:08:28', 'Dương', 81),
(6, 'Tháng Tư Là Lời Nói Dối Của Em', '[F]Mùa xuân có [G]em như chưa bắt [Em]đầu [Am ]  \r\n[F]Và cơn gió [G]như khẽ mơn man [Em]lay từng nhành hoa rơi [Am ] \r\n\r\n[F]Em đã bước [G]tới như em đã [Em]từng [Am ]  \r\n[F]Chạy trốn với [G]anh đến cánh đồng [Asus4]xanh [A ]    \r\nKhúc [F]nhạc hoà cùng nắng [G]chiều dịu dàng \r\nđể [Em]mình gần lại [Am]mãi \r\n\r\nNói [F]lời thì thầm những [G]điều thật thà đã [C]giữ trong tim mình [C7 ]  \r\nNhững [F]chặng đường dài ngỡ [G]mình mệt nhoài đã [Em]một lần gục [Am]ngã  \r\n\r\nTháng [F]tư có em ở [G]đây nhìn tôi mỉm [Asus4]cười [A ]  \r\n\r\nĐK:  \r\n\r\nNhững cánh hoa phai [F]tàn thật [G]nhanh, \r\nem có bay [Em]xa, \r\nem có đi [Am]xa mãi  \r\n\r\nTháng tư đôi khi [F]thật mong [G]mạnh để mình nói [C]ra những câu chân thật [C7 ]  \r\nGiá như tôi một [F]lần tin [G]em, cô gái tôi [Em]thương, này hoá theo [Am]mây gió  \r\n\r\nĐể [F]lại tháng [Em]tư ở [Am]đó  \r\n  ', 'Hà Anh Tuấn', 'Phạm Toàn Thắng', 'Ballad', 'Ballad', 'F', 0, 'https://www.youtube.com/watch?v=UCXao7aTDQM', '2019-01-03 16:08:42', 'Hải', 37),
(7, 'Sai Người Sai Thời Điểm', '[G]Chuyện tình yêu lúc [D]nào cũng thế. \r\nĐi [Em]mãi bao năm lê thê mong tìm được [Bm]ai trên lối về  \r\nĐể [C]dành một đời yêu [D]thương trao [Bm]về nhau không vấn [Em]vương \r\n\r\n[Am]Chỉ mong rằng ta mãi bên cạnh dù đời [D]còn bao gió sương    \r\n[G]Và chuyện tình yêu bây [D]giờ vẫn thế  \r\nAnh [Em]vẫn luôn yêu em thôi dẫu em giờ [Bm]đây đã khác rồi  \r\nTình [C]yêu mà anh vun vén [D]bao lâu kết [Bm]thúc khi em nói [Em]câu  \r\nEm [Am]thấy chúng ta không hợp mình chia [D]tay nhé    \r\nMình gặp nhau [G]đúng hay sai mà [Bm]đã chia hai  \r\nCoi [Em]nhau như chẳng tồn [D]tại  \r\n\r\nHợp nhau là [C]do mình thôi luôn [D]sống thứ tha vì [G]nhau[G7 ]  \r\n\r\nTìm được nhau [C]dễ dàng đâu  \r\nCó [D]phải bên nhau một [Bm]ngày hay bốn năm [Em]hôm?  \r\nNay em nói [Am]câu không hợp là do duyên số hay [D]sao?   \r\n Vậy em có [G]chắc bao năm mọi [Bm]thứ yêu thương  Em [Em]trao riêng mỗi anh [D]không? \r\n Mình gặp nhau [C]sai thời gian và [D]sai người phải không [G]em?[G7 ]  \r\n\r\nNhìn người mà [C]anh từng thương  \r\nCứ [D]thế đi xa từng [Bm]bước trên phố quen [Em]thuộc  \r\nMột người [Am]đứng trông một người [Bm]khuất xa [Em]dần﻿', 'Thanh Hưng Idol', 'Thanh Hưng Idol', 'Nhạc Trẻ', 'Ballad', 'G', 0, 'https://www.youtube.com/watch?v=5R5YnEbp2CU', '2019-01-03 16:09:00', '', 19),
(8, 'Vô Tình', '[Fmaj7]Đôi khi tôi vô tình nhìn [Em7]thấy anh  \r\nAnh vô tình đi [Dm7]rất nhanh  \r\nTrái tim [Cmaj7]rung động theo [C7]từng câu hát    \r\n[Fmaj7]Lấp lánh những ánh đèn chiếu [Em7]xung quanh  \r\nTôi thấy mình trong [Dm7]mắt anh  \r\n\r\nNhưng có [Cmaj7]lẽ anh [C7]không nhận ra.    \r\n[Fmaj7]Tôi muốn nói anh nghe những [Em7]tầm thường \r\ncủa thế giới ở [Dm7]ngoài kia  Anh có [Cmaj7]biết không? [C7 ]  \r\n[Fmaj7]Tôi muốn nói ra hết nhưng \r\n[Em7]lại sợ  \r\nMình không thể đi [Dm7]cùng nhau  Sợ người [Cmaj7]vô tình.   \r\n Vô tình lạc mất [Fmaj7]anh, giữa thênh thang do dự [Em7]rối ren  \r\nAnh có thể nắm tay [Dm7]em để em không phải tìm anh nữa [Cmaj7]không?  \r\n\r\nSao [C7]anh vẫn chưa thấy [Fmaj7]em đã cố gắng để mình [Em7]giống như  \r\nEm vô tình như thế [Dm7]thôi!  \r\nEm vô tình yêu lấy [Cmaj7]anh mà sâu đậm [C7]như thế này?    \r\n[Fmaj7]Cùng em đi thật xa đến \r\n\r\n[Em7]mọi nơi phương trời lạ  \r\nPhiêu [Dm7]bạt như những áng mây giữa đất [Cmaj7]trời  \r\n[Fmaj7]Rồi anh sẽ nhận ra những [Em7]thứ sâu trong lòng em  \r\n[Dm7]Vô tình như là một giấc mơ dài [Cmaj7]cả đời. ', 'Hoaprox, Xesi', 'Hoaprox, Xesi', 'Nhạc Trẻ', 'Ballad', 'C', 0, 'https://beta.mp3.zing.vn/bai-hat/Vo-Tinh-Xesi-Hoaprox/ZW9DC99A.html', '2019-01-03 15:55:50', '', 16),
(9, 'Mãi Mãi Sẽ Hết Vào Ngày Mai', 'Verse: \r\n[C]Đừng nói sẽ [F]yêu, trọn 1 [Em]kiếp, vì mình đâu [E]biết mai sẽ ra [Am]sao \r\nĐường đời đổi [F]thay [Fm]mau, thì [Dm]chắc gì ta sẽ yêu thật [G]lâu \r\n[C]Đừng nói cùng [F]anh, vượt trùng [Em]khơi, tận cùng thế [E]giới \r\nRồi lỡ nơi chân [Am]trời, mình lạc mất [Dm]nhau, người ơi \r\nVì [F]những lời hứa ma ta chẳng thể [G]giữ \r\n \r\nChorus : \r\n[C]Yêu thôi, đừng [Em]nói những lời phù [Am]phiếm \r\nHãy yêu nhau [G]chân thành, vì ngày dài [F]trôi qua rất nhanh \r\nLỡ [Em]đâu giây cuối [A]cùng, mọi [Dm]thứ “ta đã” sẽ trở thành quá [G]khứ ! \r\n \r\nHỡi người [C]ơi, anh đâu nào [Em]biết, vì cứ [Am]ngỡ ta đã yêu 1 đời \r\nVậy [G]sao đến hôm nay lại đổi [F]thay \r\nTinh yêu có thể [Em]trả lời được [A]không, ngoài [Dm]kia duyên \r\ntình có thể vẹn [G]đôi, riêng tôi thì [C]không ! \r\n \r\nVerse 2 : \r\n[C]Được mất gần [F]xa \r\nLà chuyện [Em]thời gian \r\nĐể mình gặp [E]nhau nơi thế gian [Am]thay màu \r\nĐể nơi trái [Dm]tim lầm than \r\nLiệu [F]ta sẽ yêu trọn kiếp, trọn [G]hơi thở ! \r\n \r\nChorus : \r\n[C]Yêu thôi, đừng [Em]nói những lời phù [Am]phiếm \r\nHãy yêu nhau [G]chân thành, vì ngày dài [F]trôi qua rất nhanh \r\nLỡ [Em]đâu giây cuối [A]cùng, mọi [Dm]thứ “ta đã” sẽ trở thành quá [G]khứ ! \r\n \r\nHỡi người [C]ơi, anh đâu nào [Em]biết, vì cứ [Am]ngỡ ta đã yêu 1 đời \r\nVậy [G]sao đến hôm nay lại đổi [F]thay \r\nTinh yêu có thể [Em]trả lời được [A]không, ngoài [Dm]kia ai cũng có thể thành [G]đôi... \r\nCoda : \r\n... [F]Ai cũng phải có vết [Em]thương lòng, vì [E]yêu đâu giống như [Am]mơ \r\nChẳng co phép [F]màu nào giữ lấy, [Fm]khi bàn tay một ai muốn rời [G]xa... \r\n \r\n...người [C]ơi, anh đâu nào [Em]biết, vì cứ [Am]ngỡ ta đã yêu 1 đời \r\nVậy [G]sao đến hôm nay lại đổi [F]thay \r\nTinh yêu có thể [Em]trả lời được [A]không, ngoài [Dm]kia duyên \r\ntình có thể vẹn [G]đôi.. mình [F]tôi ôm nỗi [G]đau vì \r\nai đã đi [C]rồi ', 'Andiez', 'Andiez', 'Nhạc Trẻ', 'Ballad', 'C', 4, 'https://beta.mp3.zing.vn/bai-hat/Mai-Mai-Se-Het-Vao-Ngay-Mai-Andiez/ZW9E6908.html', '2019-01-03 15:25:08', 'Hải', 5),
(10, 'Chiều Nay Không Có Mưa Bay', '[C]Nắng vàng góc phố, hoa [E7]nghiêng dài trong mắt \r\nVà [Am]thu nhẹ [G]trôi rất [F]êm  \r\nChiều [Dm]nay không có mưa [G]bay \r\nVà [Em]anh ngủ quên đã [Am]lâu rồi \r\nNgủ [Dm]quên trên phố một [G]mình. \r\n[C]Mưa là khúc hát, [E7]mưa là năm tháng \r\nCòn [Am]em là những nhớ [G]mong của đời [F]anh \r\nChiều [Dm]nay không có mưa [G]bay \r\nChỉ [Em]có những con đường [Am]dài \r\nCùng [Dm]anh ngồi hát vu [G]vơ.\r\n\r\nDK: \r\n\r\nChiều nay không [C]có mưa rơi ướt [G]trên đôi bờ [Am]vai \r\nChiều nay không [F]có mắt em [G]cười như lúc [C]xưa \r\nDường như góc [F]phố cũng biết [G]buồn, \r\nThả hoa [Em]bay khắp con [Am]đường \r\nChiều nay [Dm]không có mưa rơi anh lặng [G]im. \r\nRồi phiêu linh [C]hát để gió cuốn [G]anh đi mãi xa [Am]vời \r\nLàm mây phiêu [F]lãng nơi cuối [G]trời tìm [C]em \r\nPhải làm sao [F]để có nụ [G]cười một ngày [Em]mưa bay năm [Am]nào \r\nChiều nay [Dm]không có mưa rơi, chiều nay [Fm]không có những mộng [G]mơ. \r\n* [C]Xa dần năm tháng, [Em]con đường vẫn thế \r\nChỉ [F]mưa và anh đứng [G]đây chờ [C]em. ', 'Thái Tuyết Trâm', 'Minh Tuấn', '', 'Slow', 'C', 0, 'https://www.youtube.com/watch?v=8AaMb9kxhRI', '2019-01-03 16:10:51', '', 28),
(11, 'Lạ Lùng', 'Kìa màn [C]đêm hiu hắt [G/B], \r\n Mang tên [A7]em quay về trong ký [Dm7]ức , \r\n Của [G]anh qua [C]thời gian  \r\nChiều lặng [C]im nghe [G/B]gió  \r\nĐung đưa [A7]cây ,  \r\nNhư là bao nỗi [Dm7]nhớ cuốn [G]anh trôi [C]về đâu ?  \r\nNày [F]gió đừng [G]hát ,  \r\nVà [E7]mang nỗi nhớ [Am]chạ̣y đi [F]quên âu lo,  \r\nQuên [G]hết suy tư [C]một đời. [C7 ]  [F]Mưa trong anh sẽ [G]vơi ,  \r\nNhưng [E]đôi môi đang vấn [Am]vương ,  \r\n\r\n[F]Chỉ tình cờ nhìn em rồi mang theo [G]những cơn đau thét gào.    \r\nLạ lùng em [C]tới….[E]ới , tới [Am]bên anh trong chiều đông xa vắng…  mà [F]sao  Giờ đây nhìn [G]lại chẳng còn thấy [C ]em. [C7 ]  \r\nLạ lùng em [C]với....[E]gió hát [Am]lên câu ca làm anh thao thức, \r\n Mà [F]bao say mê nồng [G]nàn giờ đã phai [C]mau  \r\nKìa [F]nắng ngập [G]tràn , những giấc [Em]mơ lại vừa bay [A7]đi ,  \r\nGạt [F]hết cuộc đời lẻ loi. \r\nThôi mình [G]anh, lại ngồi nhớ [C]em! ', 'Vũ', 'Vũ', 'Nhạc Trẻ', 'Ballad', 'C', 0, 'https://beta.mp3.zing.vn/bai-hat/La-Lung-Vu/ZW78E6A9.html', '2019-01-03 08:56:53', '', 5),
(12, 'Người Tình Mùa Đông', 'Đường vào [F ]tim em ôi băng [Am ]giá  Trời mùa [Dm ]đông mây vẫn hay đi [Am ]về \r\nVẫn [Gm ]mưa mưa rơi trên đường thầm [Dm ]thì\r\nVì [A# ]đâu mưa em không [C ]đến \r\nĐường vào [F ]tim em mây giăng [Am ]kín \r\n Bàn chân [Dm ]anh trên lối đi không [Am ]\r\nthành  \r\nNhững [Gm ]đêm khuya mưa buồn một [Dm ]mình \r\nCó [C ]khi cho ta quên cuộc [Dm ]tình \r\nTừng cơn [F ]mưa hắt hiu bên ngoài song [Am ]thưa \r\nLắm khi mưa làm hồn [A7 ]ta nhớ mãi ngày [Dm ]qua \r\n Nhớ con [A# ]phố xưa vẫn âm thầm đợi [F ]chờ  \r\nNhớ đôi vai [Gm ]ngoan em sợ trời mưa [Am ]gió  \r\n  Từng ngày [F ]ta vẫn đưa em về qua [Am ]phố  \r\nVẫn chim cao trời mưa [A7 ]lũ vẫn tiếng buồn [Dm ]xưa  \r\nÔi bàn [A# ]tay ai đã dắt em chiều [C ]nay   \r\n Đường vào [F ]tim em bao cơn [Am ]sóng  Để tình [Dm ]anh sắp đến xuân hoa [Am ]mộng  Trái [Gm ]tim em muôn đời lạnh [Dm ]lùng  \r\nHỡi [C ]ơi, trái tim mùa [Dm ]đông ', 'Hà Anh Tuấn', 'Nhạc ngoại', 'Trữ Tình', 'Chachacha', 'F', 0, 'https://www.youtube.com/watch?v=dns2WLu8Su8', '2019-01-03 16:10:22', '', 2),
(13, 'Anh Đếch Cần Gì Nhiều Ngoài Em', 'Và anh [Am]đếch cần gì nhiều ngoài [Am]em \r\n Và anh [Em]đếch cần gì nhiều ngoài [Em]em  \r\nVà anh [Am]đếch cần gì nhiều ngoài [Am]em  \r\nVà anh [Em]đếch cần gì nhiều ngoài [Em]em    \r\nVer1:  [Am]Anh như con cáo em như [Am]một cành nho xanh  \r\nKhi em [Em]còn trẻ và đẹp em lại [Em]không dành cho anh  \r\nTrong lòng [Am]anh là kho xăng, nụ cười [Am]em là mồi lửa  \r\nEm phá [Em]vỡ đi quy tắc, rồi bỏ [Em]mặc anh ngồi sửa \r\n Anh như [Am]biến thành người nhện, vì trong [Am]lòng nhiều tơ vương  \r\nNhớ em [Em]tốn nhiều calo, thế nên [Em]anh gầy trơ xương  \r\nỞ trong [Am]xóm anh rất ngoan, chẳng ai [Am]thấy anh say mèm \r\n Mẹ anh [Em]dặn anh đủ thứ, nhưng quên [Em]dặn đừng say em  [Am]\r\nNhư con cuốn chiếu, anh [Am ]có rất nhiều chân thật  [Em]\r\nBài hát này ngọt vì đám tụi [Em]anh rất thân mật  [Am]\r\nAnh như con cáo và em [Am]vẫn cành nho xanh  Nhưng mà [Em]em trẻ và đẹp, em lại [Em]không dành cho anh    \r\nTa đã [Am]đi tìm về thương [Am]nhớ  Ta đã [Em]đi đã đi tìm đi [Em]tìm \r\n Ta đã [Am]đi tìm về quá [Am]khứ  \r\nTa đã [Em]đi đã đi tìm đi [Em]tìm    ĐK:  Và anh [Am]đếch cần gì nhiều ngoài [Am]em  \r\nÔi một [Em]giấc mơ chơi vơi nhiều [Em]đêm  \r\nVà anh [Am]đếch cần gì nhiều ngoài [Am]em  \r\nThương một [Em]giấc mơ ôm ta nhiều [Em]đêm    \r\n[Am]Một ngày cùng em, uống đến [Am]thoáng say là đủ  [Em]\r\nKệ đời ngả nghiêng, mình nằm dưới [Em]tán cây mà ngủ  [Am]\r\nSẽ thật là tuyệt nếu rơi [Am]vào một chiều thu  [Em]\r\nAnh cưa em đổ, em gọi [Em]anh là tiều phu  \r\nAnh có [Am]thể có danh tiếng, nếu như [Am]mặt anh dày thêm  \r\nAnh có [Em]thể có nhiều tiền, nếu anh [Em]cày ngày cày đêm  \r\nNhưng [Am]như một giấc mơ, bị em [Am]chối bỏ trong chiều  \r\nAnh [Em]không có được em, dù cho [Em]cố bỏ công nhiều  \r\nNồng độ [Am]cồn em bao nhiêu, sao cứ [Am]làm anh lảo đảo  \r\nEm chỉ [Em]mang lại chua cay, như là [Em]gói mì Hảo Hảo  \r\n[Am]Một lần chơi lớn để xem [Am]em có trầm trồ  Vì yêu [Em]em, anh như [Em]mang hết con tim đi cầm [Am]đồ.......    ĐK:  \r\nVà anh [Am]đếch cần gì nhiều ngoài [Am]em  Ôi một [Em]giấc mơ chơi vơi nhiều [Em]đêm  \r\nVà anh [Am]đếch cần gì nhiều ngoài [Am]em  \r\nThương một [Em]giấc mơ ôm ta nhiều [Em]đêm    \r\nVà anh [Am]đếch cần gì nhiều ngoài [Am]em \r\n Và anh [Em]đếch cần gì nhiều ngoài [Em]em \r\n Và anh [Am]đếch cần gì nhiều ngoài [Am]em  Và anh [Em]đếch cần gì nhiều ngoài [Em]em  [AmAmEmEm ]  [AmAmEmEm] ', 'Đen, Vũ', 'Đen Vâu', 'Rap Việt', 'Slow Rock', 'Am', 2, 'https://www.youtube.com/watch?v=KdrbBJNFwGw', '2019-01-03 16:15:09', 'Hải', 16),
(14, 'Anh Đang Ở Đâu Đấy Anh', '[Em]Em, [D]anh, [C]cô ta, chuyện [Bm]chúng mình  [Am]Giờ đây phải [G]làm sao [F#m7b5]yên vui như [B7]ban đầu  [Em]Nhớ, [D]đau, [C]còn người vui [Bm]nơi khác  [Am]Hỏi phải chăng người [G]ta chẳng đếm được [Am]ra mình là người [B7]thứ ba    [Em]Anh đang ở đâu [D]đấy anh [C]có hay về [G]em này  [Am]Anh chắc đang bận với [Em]nơi có tiếng yêu mới [F#m7b5]nên anh đâu [B7]nào để ý  [Em]Anh đang ở đâu, [D]có trở về không [C]hay lạc nhau đến [G]muôn đời  Ngày nhìn [Am]anh ra đi [G]mưa ngoài trời trắng xóa [F#m7b5]như nỗi [B7]buồn trong [Em]em    [Em]Đếm, [D]mong, [C]con tim sao [Bm]yếu mềm  [Am]Vì anh đã [G]vội quên [F#m7b5]yêu thương lúc [B7]ban đầu  [Em]Mắt, [D]môi, [C]chuyện buồn em [Bm]che giấu  [Am]Thấy nhưng em lờ [G]đi, chẳng nói một [Am]câu đâu phải chẳng [B7]biết được    [Em]Anh đang ở đâu [D]đấy anh [C]có hay về [G]em này  [Am]Anh chắc đang bận với [Em]nơi có tiếng yêu mới [F#m7b5]nên anh đâu [B7]nào để ý  [Em]Anh đang ở đâu, [D]có trở về không [C]hay lạc nhau đến [G]muôn đời  Ngày nhìn [Am]anh ra đi [G]mưa ngoài trời trắng xóa [F#m7b5]như nỗi [B7]buồn trong [Em]em    [Em]Anh đang ở nơi [D]rất xa [C]chắc chẳng thể [G]quay về  [Am]Em vẫn [Em]chờ anh [F#m7b5]sao chẳng có [B7]điều kì tích    LÊN 1 TONE  [F#m]Anh đang ở đâu [E]đấy anh [D]có hay về [A]em này  [Bm]Anh chắc đang bận với [F#m]nơi có tiếng yêu mới [G#m7b5]nên nên anh sẽ[C#7]chẳng về nữa  [F#m]Anh đang ở đâu, [E]Anh đang ở đâu, [D]ta lạc nhau đến [A]muôn đời rồi  Ngày nhìn [Bm]anh ra đi [A]mưa ngoài trời trắng xóa [G#m7b5]như nỗi [C#7]buồn trong [F#m]em ', 'Hương Giang Idol', 'Andiez', 'Nhạc Trẻ', 'Ballad', 'Em', 4, 'https://www.youtube.com/watch?v=RLGiEBsQ1Xg', '2019-01-02 02:18:30', '', 1),
(15, 'Y.E.U', '1. [C]Yêu, là cùng nhau trong tay đi dưới [G]con đường  Là cùng trao cho nhau ngọt môi [Am]hôn  Là vòng tay yêu thương ôm [F]mãi không rời  Từng phút giây tuyệt vời.    [C]Yêu, là ngày em bên anh không chút [G]ưu phiền  Từng buồn lo trôi qua ngày bình [Am]yên  Nồng nàn ta trao nhau giấy [F]phút tuyệt vời  Nguyện thề luôn bên nhau [C]mãi.    Dù thời gian trôi qua vẫn luôn [G]bên người  Dù ngày tháng phôi pha ta vẫn [Am]không cách rời  Bên nhau suốt đời, cùng [F]xây giấc mơ chung đôi.    ĐK:  [C]Hãy bên em thật gần [G]nhé anh  Để cảm nhận [Am]những thứ yêu thương  Từ trong [F]trái tim này  Dành hết cho người.    [C]Hãy trao em nụ hôn [G]đắm say  Ngọt ngào như [Am]phút giây ban đầu  Ngày [F]nắng xanh ngời  Nguyện ước có nhau trọn [C]đời.    2. [C]Yêu, là bình minh mỗi sớm có anh [G]bên mình  Là hoàng hôn mênh mang từng con [Am]phố  Mình cùng tay trong tay đi [F]giữa cuộc đời  Nguyện thề luôn bên nhau [C]mãi.    Dù thời gian trôi qua vẫn luôn [G]bên người  Dù ngày tháng phôi pha ta vẫn [Am]không cách rời  Bên nhau suốt đời  Cùng [F]xây giấc mơ chung đôi. ', 'Min', 'Khắc Hưng', 'Nhạc Trẻ', 'Ballad', 'C', 3, 'https://beta.mp3.zing.vn/bai-hat/Y-E-U-Acoustic-Version-MIN/ZW70U88I.html', '2019-01-02 02:20:14', '', 1),
(16, 'Yêu 5', 'Xin những bối [F]rối này cứ thế lên [G]ngôi \r\nXin con tim rẽ [Em7]lối tìm giây phút nghẹn [Am7]lời \r\nCho thêm chơi [F]vơi, để những ánh mắt đôi [G]môi, \r\nChạm nhau mang theo gọi [Em7]mời [Am7 ] \r\n \r\nXin cho ta [F]tan vào những đắm đuối miên [G]man \r\nKhi em ghé [Em7]ngang đời chợt mang sắc hương thiên [Am7]đàng \r\nVà cho những ấm [F]áp lại đến lấp kín nhân [G]gian \r\nNgày ta yên vui cùng [Em7]nàng [A7 ] \r\n \r\nPre-hook: (Nên rải nhẹ hoặc quạt hẳn xuống 1 lần theo nhịp vì đây là đoạn feel) \r\nNhẹ nhàng âu yếm [F]giữa chốn mơ \r\nCùng tìm [G]kiếm bao ý thơ \r\nĐể [Em7]đắm say trong tiếng nhạc du [Am7]dương \r\nHồn sa theo [F]bước ta ngẩn ngơ \r\nDù ngàn [G]kiếp ta vẫn chờ \r\nChỉ cần có [Em7]phút giây này trao yêu [A7]thương \r\n \r\nHook: (Nên áp dụng quạt và palm thùng sẽ rất feel, không biết thì cứ Blue) \r\nCuz baby it’s always [F]you \r\nIt\'s always [G]you \r\nIt\'s always [Em7]you \r\nIt\'s always [Am7]you...always you... \r\n(x2) Lăp lại \r\n \r\nRap: vòng F G Em7 Am7 \r\nTa như đi qua [F]hết bao nhiêu mê say trên đời \r\nNhư yêu thêm cả nghìn [G]kiếp khi ta một giây bên người \r\nVì chỉ cẩn một [Em7]ánh nhìn mà em trao \r\nLà tuổi xuân của ta như [Am7]hóa được thành chiêm bao \r\nVới mỗi sáng thức [F]giấc nghe em bên ta vui cười \r\nCho đêm ta ngây [G]ngất, ru tai êm qua đôi lời \r\nĐầy ngọt ngào và trong [Em7]veo, cùng hòa làm trăng sao \r\nDìu dắt đôi tim bên [Am7]nhau đi theo bao yêu thương dâng trào \r\n \r\nVà ta xin đánh đổi một [F]rừng tia nắng để lấy chút hơi ấm của em \r\nXin đổi đi [G]hết tiền bạc danh tiếng, những thứ hàng trăm người thèm \r\nBởi cả [Em7]ngàn điều phù phiếm đâu bằng một thoáng môi mềm \r\nKhi đời này [Am7]sẽ mang đầy nuối tiếc nếu không có nàng ở bên \r\nNhìn [F]em ta mới thêm yêu từng khoảnh khắc \r\nMang hết tương [G]tư giấu vào theo từng bản nhạc \r\nĐể mai này tình [Em7]nở như muôn hoa không tàn sắc \r\nLưu giữ mãi nơi [Am7]này một câu chuyện ngàn năm ', 'Rhymastic', 'Rhymastic', 'Nhạc Trẻ', 'Ballad', 'F', 3, 'https://beta.mp3.zing.vn/bai-hat/yeu-5-Rhymas/ZW78FFI6.html', '2019-01-02 02:19:52', 'Hải', 1),
(18, 'Mưa Trên Cuộc Tình', 'Từng hạt [C ]mưa rơi tí tách bên hiên nhà [Am ]nàng \r\nLòng thầm [F ]mong một ánh mắt thấp thoáng mong [C ]chờ \r\nNgười yêu [F ]hỡi mãi mãi yêu [C ]nàng \r\nEm dù [E ]biết vẫn cứ hững [Am ]hờ \r\nMặc cho [F ]anh đêm đêm vẫn mong cuộc tình đôi [G ]ta \r\n\r\nDK:\r\n\r\nGiọt buồn [C ]rơi rơi lặng lẽ trên con đường [Am ]dài \r\nMột mình [F ]anh lòng se sắt với gió đông [C ]về \r\nRồi thôi [F ]hết những ước mơ [C ]dài \r\nMưa còn [E ]rớt rớt trên nỗi [Am ]sầu \r\nLạnh đôi [F ]vai em ơi biết chăng tim anh lẻ [C ]loi \r\n\r\n\r\nKỷ niệm [C ]xưa em ơi nhớ chăng \r\nBao lời [Am ]yêu đã nói hôm nào \r\nTừng cơn [F ]mưa đôi ta có nhau phút giây thần [C ]tiên \r\nGiờ mình [Em ]anh trên con phố xưa \r\nNgồi lặng [Am ]lẽ ngắm mây dần trôi \r\nMặc [F ]cho thời gian hờ hững xô nhau mãi [G ]đâu \r\n\r\n\r\nChuyện tình [C ]yêu đôi ta rẽ dôi \r\nBao lời [Am ]yêu đã vỗ cánh rồi \r\nThầm cầu [F ]mong cho em hãy quên những kỷ niệm [C ]xưa \r\nCuộc tình [Em ]ta tan theo giấc mơ \r\nHình bóng [Am ]cũ mãi trông về đâu \r\nGiờ đã [F ]hết bao nhiêu yêu [G7 ]thương cô đơn lối [C ]về. ', 'Edward Dương', 'Lê Quang', 'Nhạc trẻ', 'Ballad', 'D', 2, 'https://www.nhaccuatui.com/bai-hat/mua-tren-cuoc-tinh-acoustic-cover-edward-duong-nguyen.uhbTyuba5AWw.html', '2019-01-03 16:10:12', 'Đại', 17);

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `firstname` varchar(32) COLLATE utf8_unicode_ci NOT NULL,
  `lastname` varchar(32) COLLATE utf8_unicode_ci NOT NULL,
  `email` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `contact_number` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `address` text COLLATE utf8_unicode_ci NOT NULL,
  `password` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `confirm_password` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `access_level` varchar(16) COLLATE utf8_unicode_ci NOT NULL,
  `access_code` text COLLATE utf8_unicode_ci NOT NULL,
  `status` int(11) NOT NULL,
  `created` datetime NOT NULL,
  `modified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `users`
--

INSERT INTO `users` (`id`, `firstname`, `lastname`, `email`, `contact_number`, `address`, `password`, `confirm_password`, `access_level`, `access_code`, `status`, `created`, `modified`) VALUES
(1, 'Dũng', 'Lê', 'mike@example.com', '0999999999', 'Blk. 24 A, Lot 6, Ph. 3, Peace Village', '$2y$10$AUBptrm9sQF696zr8Hv31On3x4wqnTihdCLocZmGLbiDvyLpyokL.', '$2y$10$AUBptrm9sQF696zr8Hv31On3x4wqnTihdCLocZmGLbiDvyLpyokL.', 'Customer', 'DTaYBon8tecqWdY4evjsBcTPckUDRlKG', 1, '2018-12-28 20:23:20', '2018-12-28 12:23:41'),
(2, 'Đạt', 'Nguyễn Văn', 'darwin@example.com', '9331868359', 'Blk 24 A Lot 6 Ph 3\r\nPeace Village, San Luis', '$2y$10$tLq9lTKDUt7EyTFhxL0QHuen/BgO9YQzFYTUyH50kJXLJ.ISO3HAO', '$2y$10$tLq9lTKDUt7EyTFhxL0QHuen/BgO9YQzFYTUyH50kJXLJ.ISO3HAO', 'Customer', 'wUIfU9VrUJm5Z712Ln4dLiywpHjxlXDj', 1, '2014-10-29 17:31:09', '2018-12-27 10:13:34'),
(3, 'Dương', 'Lăng Đại', 'duong62@gmail.com', '0359973579', 'Cầu Giấy', '$2y$10$8/ZlnenFCsuxxYqHOW6n9O.EnbBL1iW41kpV5mF1EiqYrKvmonbA2', '$2y$10$8/ZlnenFCsuxxYqHOW6n9O.EnbBL1iW41kpV5mF1EiqYrKvmonbA2', 'Admin', 'xFta3mzNPvQ8UT93HznN1nu4HXADIIeU', 0, '2018-12-10 12:38:59', '2019-01-02 08:43:27'),
(4, 'Hiền', 'Nguyễn Thanh', 'thanhhien94@gmail.com', '01683071238', '1/31 Bùi Xương Trạch', '$2y$10$rGOrsQ9Xwr/ll/eESgNuh.FcD7LboV4qm79VqeMsV5NCAQlvRMdsO', '$2y$10$rGOrsQ9Xwr/ll/eESgNuh.FcD7LboV4qm79VqeMsV5NCAQlvRMdsO', 'Customer', 'lj58lm8f6gHzZlfuzVqf3GmwqzPROWfB', 0, '2018-12-30 10:25:28', '2018-12-30 02:25:46'),
(5, 'Hải', 'Nguyễn', 'thanhhai7698@gmail.com', '0383071238', '1/31 Bùi Xương Trạch', '$2y$10$raC90Toh1gr5kVj4JccRzOQZkKeN1QkNtvzdUtpkXAn8/1XhHmdhi', '$2y$10$DfLc6hgHMACXA0SzF6qZROhEye/73ed30wvTT7tukYB3Brb3zPrhW', 'Admin', 'HuJcFjHmsAVyrggczstDEubyuVM7oBlG', 1, '2018-12-20 00:35:19', '2018-12-26 18:51:47'),
(6, 'Hải', 'Nguyễn Thanh', 'haint62@wru.vn', '0383071238', '1/31 Bùi Xương Trạch', '$2y$10$/H6PcqjjTGxvUhYhr11UyOXmp4wbfW8/9f3hLH4C.lXw.DByg72xG', '$2y$10$LpROYJDJeF2hVXGMvaAoEu9scpYPb6VvpCJ6uOtQsae9lmD4pNDai', 'Customer', 'KYgoYc3ygkLMVZDcZVKBPOjrSbYZPHxT', 1, '2018-12-30 16:28:51', '2019-01-02 09:08:52'),
(7, 'Đại', 'Dương', 'langdaiduong98@gmail.com', '01686837225', 'Hà Nội', '$2y$10$st2CkKPWsmYo/sqF9VUS5uQu19vtUNJNNjhi9U7dtWXa..XIeqCfq', '$2y$10$KU.QbdoQTcuNjUSRk5jWre5rH3qGMlsOaaclhQnD4OFRrjjEdTvs.', 'Admin', 'SZTjqOyIetLaJ8dzPuXY2r65FKjAuSC9', 1, '2019-01-03 00:32:51', '2019-01-03 14:43:03');

--
-- Chỉ mục cho các bảng đã đổ
--

--
-- Chỉ mục cho bảng `baihat`
--
ALTER TABLE `baihat`
  ADD PRIMARY KEY (`Mabh`);

--
-- Chỉ mục cho bảng `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT cho các bảng đã đổ
--

--
-- AUTO_INCREMENT cho bảng `baihat`
--
ALTER TABLE `baihat`
  MODIFY `Mabh` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=19;

--
-- AUTO_INCREMENT cho bảng `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
